<?php if(!defined('BASEPATH')) die('Direct access not allowed'); ?>

<h1>Terms of Use Agreement</h1>

<p>Welcome to the CGI Solution LLC website. We maintain this web site as a service to our visitors and customers. By using our site, you are agreeing to comply with and be bound by the following terms of use. Please review the following terms carefully. If you do not agree to these terms, you should not review information or obtain goods or products from this site.</p>
<h4>1. Acceptance of Agreement.</h4>
<p>You agree to the terms and conditions outlined in this Terms of Use Agreement (&quot;Agreement&quot;) with respect to our site (the &quot;Site&quot;). This Agreement constitutes the entire and only agreement between us and you, and supersedes all prior or contemporaneous agreements, representations, warranties and understandings with respect to the Site, the content, products or services provided by or through the Site, and the subject matter of this Agreement. This Agreement may be amended at any time by us from time to time without specific notice to you. The latest Agreement will be posted on the Site, and you should review this Agreement prior to using the Site.</p>
<h4>2. Intellectual Property; Limited License to Users</h4>
<p>The Materials and Services on this Site, as well as their selection and arrangement, are protected by copyright, trademark, patent, and/or other intellectual property laws, and any unauthorized use of the Materials or Services at this Site may violate such laws and the Terms of Use. Except as expressly provided herein, CGI Solution LLC and its suppliers do not grant any express or implied rights to use the Materials and Services. You agree not to copy, republish, frame, download, transmit, modify, rent, lease, loan, sell, assign, distribute, license, sub-license, reverse engineer, or create derivative works based on the Site, its Materials, or its Services or their selection and arrangement, except as expressly authorized herein. In addition, you agree not to use any data mining, robots, or similar data gathering and extraction methods in connection with the Site.</p>
<h4>3. Copyright.</h4>
<p>The content, organization, graphics, design, audio, animation, video, compilation, magnetic translation, digital conversion and other matters related to the Site are protected under applicable copyrights, trademarks and other proprietary (including but not limited to intellectual property) rights. The copying, redistribution, use or publication by you of any such matters or any part of the Site, except as allowed by Section 4, is strictly prohibited. You do not acquire ownership rights to any content, document or other materials viewed through the Site. The posting of information or materials on the Site does not constitute a waiver of any right in such information and materials. </p>
<h4>4. Trademarks.</h4>
<p>The trademarks, logos, and service marks (&quot;Marks&quot;) displayed on this Site are the property of CGI Solution LLC or other third parties. You are not permitted to use the Marks without the prior written consent of CGI Solution LLC or such third party that may own the Marks.  All other trademarks and registered trademarks are the property of their respective owners. </p>
<h4>5. Use of Software</h4>
<p>The software and accompanying documentation that is made available to download from this Site is the copyrighted and/or patented work of CGI Solution LLC and/or its suppliers. Use of the software is governed by the terms of the license agreement that accompanies or is included with such software. Such terms are available for review and are incorporated herein by this reference. You will not be able to download or install any software that is accompanied by or includes a license agreement unless you agree to the terms of such license agreement. If you do not agree to such terms, you will not be able to use the software. Absent a license agreement that accompanies the software, use of the software will be governed by the Terms of Use. You agree that you will not decompile, reverse engineer, or otherwise attempt to discover the source code of the software available on the Site. </p>
<h4>6. Limited Right to Use.</h4>
<p>The viewing, printing or downloading of any content, graphic, form or document from the Site grants you only a limited, nonexclusive license for use solely by you for your own personal use and not for republication, distribution, assignment, sub-license, sale, preparation of derivative works or other use. No part of any content, form or document may be reproduced in any form or incorporated into any information retrieval system, electronic or mechanical, other than for your personal use (but not for resale or redistribution). CGI Solution LLC reserves the right to revoke the authorization to view, download, and print the CGI Solution LLC Content and User Content available on this Site at any time, and any such use shall be discontinued immediately upon notice from CGI Solution LLC. The rights granted to you constitute a license and not a transfer of title. </p>
<h4>7. Editing, Deleting and Modification.</h4>
<p>We reserve the right in our sole discretion to edit or delete any documents, information or other content appearing on the Site. </p>
<h4>8. Indemnification.</h4>
<p>You agree to indemnify, defend and hold us and our partners, attorneys, staff and affiliates (collectively, &quot;Affiliated Parties&quot;) harmless from any liability, loss, claim and expense, including reasonable attorney’s fees, related to your violation of this Agreement or use of the Site. </p>
<h4>9. Nontransferable.</h4>
<p>Your right to use the Site is not transferable. Any password or right given to you to obtain information or documents is not transferable.  </p>
<h4>10. Disclaimer and Limits.</h4>
<p>THE INFORMATION FROM OR THROUGH THE SITE ARE PROVIDED &quot;AS-IS&quot;, &quot;AS AVAILABLE&quot;, AND ALL WARRANTIES, EXPRESS OR IMPLIED, ARE DISCLAIMED (INCLUDING BUT NOT LIMITED TO THE DISCLAIMER OF ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE). THE INFORMATION AND SERVICES MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS. WE AND OUR AFFILIATED PARTIES HAVE NO LIABILITY WHATSOEVER FOR YOUR USE OF ANY INFORMATION OR SERVICE. IN PARTICULAR, BUT NOT AS A LIMITATION THEREOF, WE AND OUR AFFILIATED PARTIES ARE NOT LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES (INCLUDING DAMAGES FOR LOSS OF BUSINESS, LOSS OF PROFITS, LITIGATION, OR THE LIKE), WHETHER BASED ON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE NEGATION OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN US AND YOU. THIS SITE AND THE INFORMATION WOULD NOT BE PROVIDED WITHOUT SUCH LIMITATIONS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US THROUGH THE SITE SHALL CREATE ANY WARRANTY, REPRESENTATION OR GUARANTEE NOT EXPRESSLY STATED IN THIS AGREEMENT. </p>
<p>ALL RESPONSIBILITY OR LIABILITY FOR ANY DAMAGES CAUSED BY VIRUSES CONTAINED WITHIN THE ELECTRONIC FILE CONTAINING THE FORM OR DOCUMENT IS DISCLAIMED. WE WILL NOT BE LIABLE TO YOU FOR ANY INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES OF ANY KIND THAT MAY RESULT FROM USE OF OR INABILITY TO USE OUR SITE. OUR MAXIMUM LIABILITY TO YOU UNDER ALL CIRCUMSTANCES WILL BE EQUAL TO THE PURCHASE PRICE YOU PAY FOR ANY GOODS, SERVICES OR INFORMATION. </p>
<h4>11. Use of Information.</h4>
<p>We reserve the right, and you authorize us, to the use and assignment of all information regarding Site uses by you and all information provided by you in any manner consistent with our Privacy Policy. </p>
<h4>12. Third-Party Services.</h4>
<p>We may allow access to or advertise third-party merchant sites (“Merchants”) from which you may purchase certain goods or services. You understand that we do not operate or control the products or services offered by Merchants. Merchants are responsible for all aspects of order processing, fulfillment, billing and customer service. We are not a party to the transactions entered into between you and Merchants. You agree that use of such Merchants is AT YOUR SOLE RISK AND IS WITHOUT WARRANTIES OF ANY KIND BY US, EXPRESSED, IMPLIED OR OTHERWISE INCLUDING WARRANTIES OF TITLE, FITNESS FOR PURPOSE, MERCHANTABILITY OR NON-INFRINGEMENT. UNDER NO CIRCUMSTANCES ARE WE LIABLE FOR ANY DAMAGES ARISING FROM THE TRANSACTIONS BETWEEN YOU AND MERCHANTS OR FOR ANY INFORMATION APPEARING ON MERCHANT SITES OR ANY OTHER SITE LINKED TO OUR SITE. </p>
<h4>13. Third-Party Merchant Policies.</h4>
<p>All rules, policies (including privacy policies) and operating procedures of Merchants will apply to you while on such sites. We are not responsible for information provided by you to Merchants. We and the Merchants are independent contractors and neither party has authority to make any representations or commitments on behalf of the other. </p>
<h4>14. Privacy Policy.</h4>
<p>Our Privacy Policy, as it may change from time to time, is a part of this Agreement. </p>
<h4>15. Payments.</h4>
<p>You represent and warrant that if you are purchasing something from us or from Merchants that (i) any credit information you supply is true and complete, (ii) charges incurred by you will be honored by your credit card company, and (iii) you will pay the charges incurred by you at the posted prices, including any applicable taxes. </p>
<h4>16. Refund Policy.</h4>
<p>CGI Solution LLC does NOT offer refunds. Once a payment has been processed, a membership for the remaining pay cycle will remain active. At the end of the cycle, the account will be closed.</p>
<p>If there are any additional fees from processing cards (fees from declined cards, etc) the member will be responsible for all applicable fees.</p>
<h4>17. Links to other Web Sites.</h4>
<p>The Site may contain links to other Web sites. We are not responsible for the content, accuracy or opinions express in such Web sites, and such Web sites are not investigated, monitored or checked for accuracy or completeness by us. Inclusion of any linked Web site on our Site does not imply approval or endorsement of the linked Web site by us. If you decide to leave our Site and access these third-party sites, you do so at your own risk. </p>
<h4>18. Information and Press Releases.</h4>
<p>The Site contains information and press releases about us. While this information was believed to be accurate as of the date prepared, we disclaim any duty or obligation to update this information or any press releases. Information about companies other than ours contained in the press release or otherwise, should not be relied upon as being provided or endorsed by us. </p>
<h4>19. Miscellaneous.</h4>
<p>This Agreement shall be treated as though it were executed and performed in Las Vegas, Nevada, and shall be governed by and construed in accordance with the laws of the State of Nevada (without regard to conflict of law principles). Any cause of action by you with respect to the Site (and/or any information, products or services related thereto) must be instituted within one (1) year after the cause of action arose or be forever waived and barred. All actions shall be subject to the limitations set forth in Section 8 and Section 10. The language in this Agreement shall be interpreted as to its fair meaning and not strictly for or against either party. All legal proceedings arising out of or in connection with this Agreement shall be brought solely in Las Vegas, Nevada. You expressly submit to the exclusive jurisdiction of said courts and consents to extra-territorial service of process. Should any part of this Agreement be held invalid or unenforceable, that portion shall be construed consistent with applicable law and the remaining portions shall remain in full force and effect. To the extent that anything in or associated with the Site is in conflict or inconsistent with this Agreement, this Agreement shall take precedence. Our failure to enforce any provision of this Agreement shall not be deemed a waiver of such provision nor of the right to enforce such provision. </p>
